name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caspianabi:latest   ## name of the repository in 
  deploy:
    #needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: appleboy/ssh-action@master
      name: Docker-Compose Remote Deployment
      with:
        host: 107.181.112.145
        port: 2233
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #docker_compose_filename: docker-compose.yaml
        script: |
           git clone git@github.com:brmyas68/CaspianAbi.git .
           cd CaspianAbi/
           docker compose down 
           docker compose up -d
        #ssh_user: ${{ secrets.SSH_USER }}
        #docker_compose_prefix: asetco
